[book]
title = "От объекта к контексту"
authors = ["Mikhail.A.I."]
language = "ru"
description = "Книга об архитектуре контроля доступа: от ролей к отношениям и контексту"

[output.html]
smart-punctuation = true
git-repository-url = "https://github.com/Taryon-ru/from-object-to-context"
edit-url-template = "https://github.com/Taryon-ru/from-object-to-context/edit/main/src/{path}"
no-section-label = true
additional-css = ["src/theme/custom.css"]
additional-js = ["src/theme/analytics.js"]

[build]
build-dir = "book"
